{% set name = "prettier" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4d2862843f2b537920a62233d27a0619d15c2999d6bae49b11a970ac06ea97fc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
