{% set name = "prettier" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 65985ae1a8df320d405228ef33298b7eb8c561f88d9872842fbcd1d5fb966f03

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
