{% set name = "prettier" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8370a7c78f9a50941c2e0d25177d94112019d8fba124ad99c5a924edf1e6c2d2

build:
  number: 0

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"  # [not win]
    - prettier --version | findstr "{{ version }}"  # [win]

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
